config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :listings do
    resources :orders
  end
  get 'pages/about'
  get 'pages/contact'
  get 'seller' => 'listings#seller'
  get 'sales' => 'orders#sales'
  get 'purchases' => 'orders#purchases'
  # get '/users',   to: 'users#index'
  root 'listings#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :orders

  validates :name, :description, :price, presence:true
  validates :price, numericality: {greater_than: 0}

  validate :correct_image_type

  private

  def correct_image_type
    if image.attached? && !image.content_type.in?(%w(image/png image/jpeg image/jpg))
      errors.add(:image, "must be a jpeg or png file!")
    elsif image.attached? == false
      errors.add(:image, "must be attached!")
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  validates :address, :city, :province, presence: true

  belongs_to :listing
  belongs_to :buyer, class_name:"User"
  belongs_to :seller, class_name:"User"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :listings
  has_many :sales, class_name:"Order", foreign_key: "seller_id"
  has_many :purchases, class_name:"Order", foreign_key: "buyer_id"
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :seller]
  before_action :check_user, only: [:edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def seller
    @listings = Listing.where(user: current_user).order("created_at DESC")
  end

  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id

    respond_to do |format|
      if @listing.save
        format.html { redirect_to seller_url, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to seller_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def listing_params
      params.require(:listing).permit(:name, :description, :price, :image)
    end

    def check_user
      if current_user!=@listing.user
        redirect_to root_url, alert: "Sorry, this listing belongs to someone else!"
      end
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /orders
  # GET /orders.json
  def sales
    @orders = Order.all.where(seller: current_user).order("created_at DESC")
  end

  def purchases
    @orders = Order.all.where(buyer: current_user).order("created_at DESC")
  end

  

  # GET /orders/new
  def new
    @order = Order.new
    @listing = Listing.find(params[:listing_id])
  end


  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @listing = Listing.find(params[:listing_id])
    @seller = @listing.user
    
    @order.buyer_id = current_user.id
    @order.listing_id = @listing.id
    @order.seller_id = @seller.id

    
    

    respond_to do |format|
      if @order.save
        format.html { redirect_to root_url, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:address, :city, :province)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<p>Copyright 2020</p>

app/views/layouts/_header.html.erb
<div class="container-fluid">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">EtsyDemo</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "About ", pages_about_path, class: "nav_link" %>
            &nbsp;
          </li>
          <li class="nav-item">
            <%= link_to "Contact", pages_contact_path, class: "nav_link" %>
          </li>
          &nbsp;
          
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <ul class="navbar-nav navbar-right">
            <% if user_signed_in? %>
              <div class="dropdown">
                <a class="btn btn-info dropdown-toggle" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Seller Account
                </a>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <li> <%= link_to "Manage Listings", seller_path, class: "nav_link dropdown-linkcolor" %> </li>
                  <li> <%= link_to "Sales History", sales_path, class: "nav_link dropdown-linkcolor" %> </li>
                </ul>    
              </div> 
              &nbsp;   
              <div class="dropdown">
                <a class="btn btn-info dropdown-toggle" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <%= current_user.name %>
                </a>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <li> <%= link_to "Purchase History", purchases_path, class: "nav_link dropdown-linkcolor"%> </li>
                  <li> <%= link_to "Edit Profile", edit_user_registration_path, class: "nav_link dropdown-linkcolor"%> </li>
                  <li> <%= link_to "Sign Out", destroy_user_session_path, class: "nav_link dropdown-linkcolor", method: :delete %> </li>
                </ul>    
              </div>   
              
            <% else %>
              <li class="nav-item">
                <%= link_to "Sign Up", new_user_registration_path, class: "nav_link" %>
              </li>
              <li class="nav-item">
              <%= link_to "Sign In", new_user_session_path, class: "nav_link"%>
              </li>
            <% end %>   
          </ul>
          
        </form>
      </div>
    </nav>
  </div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/js/bootstrap.min.js"></script>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">EtsyDemo</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "About ", pages_about_path, class: "nav_link" %>
          &nbsp;
        </li>
        <li class="nav-item">
          <%= link_to "Contact", pages_contact_path, class: "nav_link" %>
        </li>
        
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Etsydemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://js.stripe.com/v2/" %>
    <%= csrf_meta_tags %>
    <%= tag :meta, :name => "stripe-key", :content => ENV["STRIPE_PUBLIC_KEY"] %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>

  <body>
  
    <%= render 'layouts/header' %>
      <div class="container">
        <% flash.each do |name,msg| %>
          <% if msg.is_a?(String) %>
            <div class="alert alert-<%= name == :notice ? "danger" : "success" %> alert-dismissable">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <%= content_tag :div, msg, :id => "flash_#{name}" %>
            </div>
          <% end %>
        <% end %>
        <%= yield %>
      </div>
  </body>
</html>

app/views/listings/_form.html.erb
<%= form_with(model: listing, local: true) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
      <h4><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h4>

      <ul>
        <% listing.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/js/bootstrap.min.js"></script>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing, class: "btn btn-link" %> |
<%= link_to 'Back', seller_url, class: "btn btn-link" %>

app/views/listings/index.html.erb
<div class="jumbotron"
  <h1> Handcraft items from around the world </h1>
  <h2> Discover one-of-a-kind-items </h2>
</div>

<div class="center">
  <div class="row">
    <% @listings.each do |listing| %>
      <div class="col-md-3">
        <div class="thumbnail">
          <%= link_to image_tag(listing.image, :size=> "200x150"), listing %>
          <div class="caption">
            <h3><%= listing.name %></h3>
            <p><%= number_to_currency(listing.price) %> </p>
            <p><%= "Ad by #{listing.user.name}" %> </p>        
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<br>
<% if user_signed_in? %>
  <%= link_to 'Add a new listing', new_listing_path, {:style=>'font-size: large;'} %>
  <br>
<% end %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

app/views/listings/seller.html.erb
<br>
<br>
<br>
<table class="table table-bordered table-striped" >
  <thead>
    <tr>
      <th class="center"> Image </th>
      <th class="center"> Name </th>
      <th class="center"> Description </th>
      <th class="center"> Price </th>
      <th class="center"> Action </th>
    </tr>
  </thead>
  <tbody>
    <% @listings.each do |listing| %>
      <tr>
      <td class="center"> <%=  image_tag(listing.image, :size=> "150x100") %></td>
      <td class="center"> <%= listing.name %> </td>
      <td class="center"> <%= listing.description %> </td>
      <td class="center"> <%= number_to_currency(listing.price) %> </td>
      <td class="center"> 
      <div class="dropdown">
        <a class="btn btn-secondary dropdown-toggle" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Action
        </a>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <li class="dropdown-item"> <%= link_to 'View', listing_path(listing), class: "nav_link dropdown-linkcolor" %> </li>
          <li class="dropdown-item"> <%= link_to 'Edit', edit_listing_path(listing), class: "nav_link dropdown-linkcolor" %> </li>
          <li class="dropdown-item"> <%= link_to 'Delete', listing, class: "nav_link dropdown-linkcolor", method: :delete, data: { confirm: 'Are you sure?' } %> </li>
        </ul>
      </div>     
      </td>
      </tr>
    <%end %>
  </tbody>
</table>
            
<% if user_signed_in? %>
  <%= link_to 'Add a new listing', new_listing_path, {:style=>'font-size: medium;'} %>
  <br>
<% end %>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/js/bootstrap.min.js"></script>

app/views/listings/show.html.erb
<div class="row">
  <div class="col-md-6">
    <%= image_tag(@listing.image, :size=> "250x200") if @listing.image.attached? %>
  </div>
  <div class="col-md-6">
    <h3><%= @listing.name %></h3>  
    <p> <%= @listing.price %> </p>
    <p> <%= @listing.description %></p>
    <br>
    <div class="center">
    <%= link_to "Buy it now", new_listing_order_path(@listing), class: "btn btn-primary", data: { no_turbolink: true } %>
    </div>
  </div>
</div>



<% if current_user == @listing.user %>
  <%= link_to 'Edit', edit_listing_path(@listing), {:style=>'font-size: medium;'} %> 
<% end %>
&nbsp;
&nbsp;
<%= link_to 'Back', seller_url, {:style=>'font-size: medium;'} %>

app/views/orders/_form.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="thumb">
      <%= image_tag @listing.image, :size=> "200x150" %>
    </div>
  </div>
  <div class ="col-md-8">
    <%= form_with(model: [@listing, order], local: true) do |form| %>
      <% if order.errors.any? %>
      <div id="error_explanation" class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
          <h4><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h4>

          <ul>
            <% order.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div id="stripe_error" class="alert alert-danger" style="display:none">
        <noscript> Javascript is not enabled and is required for this form, First enable it in your web browser settings.</noscript>
      </div>

      <div class="form-group">
        <%= form.label :address %>
        <%= form.text_field :address, class:"form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :city %>
        <%= form.text_field :city, class:"form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :province %>
        <%= form.text_field :province, class:"form-control" %>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-md-8">
            <%= label_tag :card_number, "Credit Card Number" %>
            <%= text_field_tag :card_number, nil, {:name => nil, :'data-stripe' => "number", class:"form-control"} %>
          </div>
          <div class="col-md-4">
            <%= label_tag :card_code, "CVC" %>
            <%= text_field_tag :card_code, nil, {:name => nil, :'data-stripe' => "cvc", class:"form-control"} %>
          </div>
        </div>
      </div>
      
      <div class="form-group">
        <%= label_tag nil, "Expiration Date" %>
        <div class="row">
          <div class="col-md-3">
            <%= select_month nil, {use_two_digit_numbers: true}, {:name => nil, :'data-stripe' => "exp_month", class:"form-control"} %>
          </div>
          <div class="col-md-3">
            <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year + 10}, {:name => nil, :'data-stripe' => "exp_year", class:"form-control"} %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <%= form.submit class: "btn btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>
    

<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/js/bootstrap.min.js"></script>

app/views/orders/new.html.erb
<%= render 'form', order: @order %>

<%= link_to 'Back', listings_path %>

app/views/orders/purchases.html.erb
<div class="Center">
  <h2> Your Purchase History </h2>
</div>

<table class="table table-bordered table-striped" >
  <tr>
    <th class="center"> Image </th>
    <th class="center"> Item </th>
    <th class="center"> Price </th>
    <th class="center"> Seller </th>
    <th class="center"> Date Sold </th>
  </tr>
  <% @orders.each do |order| %>
    <tr>
    <td class="center"> <%=  image_tag(order.listing.image, :size=> "130x100") %></td>
    <td class="center"> <%= order.listing.name %> </td>
    <td class="center"> <%= number_to_currency(order.listing.price) %> </td>
    <td class="center"> <%= order.seller.name %> </td>
    <td class="center"> <%= order.created_at.strftime("%B %-d, %Y") %> </td>
    </tr>
  <%end %>
</table>
            
<br>
<% if user_signed_in? %>
  <%= link_to 'Add a new listing', new_listing_path, {:style=>'font-size: medium;'}  %>
<% end %>

app/views/orders/sales.html.erb
<div class="Center">
  <h2> Your Sales History </h2>
</div>

<table class="table table-bordered table-striped" >
  <tr>
    <th class="center"> Image </th>
    <th class="center"> Item </th>
    <th class="center"> Price </th>
    <th class="center"> Customer </th>
    <th class="center"> Date Sold </th>
  </tr>
  <% @orders.each do |order| %>
    <tr>
    <td class="center"> <%=  image_tag(order.listing.image, :size=> "150x100") %></td>
    <td class="center"> <%= order.listing.name %> </td>
    <td class="center"> <%= number_to_currency(order.listing.price) %> </td>
    <td class="center"> <%= order.buyer.name %> </td>
    <td class="center"> <%= order.created_at.strftime("%B %-d, %Y") %> </td>
    </tr>
  <%end %>
</table>
            
<br>
<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path %>
<% end %>

app/views/pages/about.html.erb
<div class="jumbotron"
</div>
<br>
<h3 class=col-md-6>Welcome to EtsyDemo!</h2>
<h5 class=col-md-6>EtsyDemo is an online marketplace for buying and selling handmade goods.</h3>

app/views/pages/contact.html.erb
<div class="jumbotron"
</div>
<br>
<br>
<br>
<p><b>Email us at admin@etsydemo.com</b></p>